### ISSUE TITLE
ImportError: No module named coniii

### ISSUE THREAD

**Issue by ekvall93** [bcdaniels/coniii#13]
Hi,

I followed the installation description. I still get ImportError: No module named coniii when running the user_guide in jupyter notebook. 

Thabk you for help.

Best regards,

Markus

**Comment by eltrompetero** [comment]
Which OS are you using? And are you using conda?

Make sure you are not opening usage_guide.ipynb in the same directory as the coniii package, and that your installation directory is in your path.

**Comment by ekvall93** [comment]
Thank you for a quick answer.

I'm using MacOS high Sierra version 10.13.2

I have tested with conda, and currently creating a new virtualenv without it (still don't working). 

I have tested: 
pip show coniii
location: venv/lib/python2.7/site-packages
and indeed in:
sys.path I find venv/lib/python2.7/site-packages

So I'm a bit confused what the problem is...

**Comment by eltrompetero** [comment]
Strange...and you're not running the notebook out of the same directory as the package just to make sure?

How about if you were to copy the coniii package out of site-packages into your local directory where you are running the notebook. That should definitely work, right?

**Comment by ekvall93** [comment]
I have cloned the git rep and have not made any changes. I then try to run jupyer notebook from the sam directory as the usage_guide.ipynb is placed.

I have copied a version of coniii from site-packages to the same directory as usage_guide.ipynb. Still not working

**Comment by eltrompetero** [comment]
Ok. I see the package is missing the __init__.py file. Must have forgotten it in the last update. Copy and paste this after unzipping it into your /venv/lib/python2.7/site-packages/coniii folder.

My mistake. I'll be updating the package on PyPI shortly.


[__init__.py.zip](https://github.com/bcdaniels/coniii/files/1921286/__init__.py.zip)

**Comment by ekvall93** [comment]
Great, thank you
